### PR TITLE
Fix error when unmounting triggered by window resize

### PR DESCRIPTION
**Pull request by bravokiloecho**
In my use of this component, I'm mounting/unmounting it based on window width. I noticed this caused a JS error because although the listeners are being removed on unmount, the requestAnimationFrame still runs and can't find an element that has since been removed from the DOM.

This PR contains two commits. The first uses linting recommendations from the code sandbox site, and the second fixes the bug.

You can see the bug in effect here (resize the window to smaller than 720 to toggle the header off): https://codesandbox.io/s/interesting-fast-ltn7d

And you can see the fix in effect here: https://codesandbox.io/s/polished-snow-ymv7j

### CODE REVIEW

**Comment by bravokiloecho** [comment]
Sorry, just realised I was behind your master. Fixing now!

**Comment by nihlton** [comment]
seems like a good fix.

to be extra certain - should we check those nodes are valid within the animationFrame callbacks?

if (document.documentElement.contains(node)) << checks if node is valid and currently part of the dom.

**Comment by bravokiloecho** [comment]
That would certainly be a belt and braces approach! But from what I can see it's not needed here because the cancel animation frame plus killing the listeners should take of it...

**Comment by nihlton** [comment]
1.1.1 published

**Comment by bravokiloecho** [comment]
Fantastic, thank you!

**Pull request merged**
